### PR TITLE
Rearranged WI/IR/IO workflows

### PR DESCRIPTION
**Pull request by bjoern234**
Moved Fmask and WaterWetness indices to Sentinel-2/Landsat preprocessing

### CODE REVIEW

**Comment by j08lue** [comment]
Seems like you branched off an older version of the repo or so? Please resolve the merge conflicts.

**Comment by j08lue** [comment]
Thanks! Could I ask you to briefly describe the changes you made? Is there anything the users will notice?

And is this ready to merge now?

**Comment by bjoern234** [comment]
Yes sure, we moved the fmask and index calculations to the pre-processing workflows. In Fmask the user doesn't have to navigate to the 'granule'-folder anymore and the cloud mask file name will be created automatically. We have documented all changes in the user guides and tech specs.

**Comment by j08lue** [comment]
Excellent, thanks. :-)

**Pull request merged**
