### PR TITLE
adapted WI and WCR workflows

### PR DESCRIPTION
**Pull request by Johannes-R-Schmid**

### CODE REVIEW

**Comment by radosuav** [comment]
@Johannes-R-Schmid thanks for the PR! Could you please describe briefly the changes. 

I also noticed that you reverted to the old styling for the workflow instructions and removed the introductory step. You probably need to download the latest Workflows plugin code from https://github.com/DHI-GRAS/qgis-processing-workflow/ and then reformat the instructions using the new styling.

**Comment by radosuav** [comment]
@Johannes-R-Schmid could you please get this and the [Fmask PR](https://github.com/GlobWetlandAfrica/GWA_scripts/pull/35) ready for merging by tomorrow lunchtime. We would like to prepare a new toolbox installation package in time for the start of Ramsar COP on Monday.

**Comment by Johannes-R-Schmid** [comment]
@radosuav the changes were mainly the addition of the Landsat and Sentinel-2 Fmask between the introduction and the TWI within the Wetland-Inventory and the Inundation Regiom workflows. Furthermore, the Fmask for Sentinel-2 in those two workflows uses our wrapper which excludes the output option.

Therefore, we needed to adapt the description. I was not able to save the workflow style with the markdown language, but as you convert the markdown language afterwards anyway, I thought that it is ok.

Nevertheless, we actually never deleted the introductory step and I still see both introductions (WI and IR) in the workflow files.

**Comment by Johannes-R-Schmid** [comment]
@radosuav I tried to create the workflow using Mardkdown instead of saving it with QGIS which automatically saves it with another style format. However, i was not able to assign the sentinel2-fmask workflow-part to the wrapper function. Instead it always referred to your script which includes the output option.
I think the important part is ".ALGORITHM:script:fmasksentinel2", but I do not know the algorithm tag of the new wrapper script. Can you tell me where I find the assignment between the Python file and for example "fmasksentinel2"?

**Comment by radosuav** [comment]
@Johannes-R-Schmid For the first part (styling of instructions) it means that you need to update your Workflows plugin. The one in QGIS plugin repository does not have this functionality yet so download the code from https://github.com/DHI-GRAS/qgis-processing-workflow/ and place it in C:\Users\user_name\.qgis2\python\plugins\processing_workflow.  

Regarding the algorithm tag, I think it should be script:maskforsentinel2forwetlandinventory. You can check it by running your script once and then looking in Processing > History. You will see a bunch of processing.runalg commands and the first argument of the latest command should be the tag of your script.

**Pull request merged**
